# Generated by Django 4.2.7 on 2026-03-02 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("sql", "SQL"),
                            ("php", "PHP"),
                            ("html", "HTML"),
                            ("css", "CSS"),
                            ("js", "JavaScript"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("code_content", models.TextField()),
                ("intent_data", models.JSONField(blank=True, default=dict)),
                ("patterns_used", models.JSONField(blank=True, default=dict)),
                ("validation_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_codes",
                        to="models.project",
                    ),
                ),
            ],
            options={
                "db_table": "generated_codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="models.project",
                    ),
                ),
            ],
            options={
                "db_table": "conversation_history",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CompanyStandards",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("php_version", models.CharField(blank=True, max_length=20)),
                ("framework", models.CharField(blank=True, max_length=50)),
                ("css_framework", models.CharField(blank=True, max_length=50)),
                ("db_engine", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "company_standards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyCodebase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("upload_path", models.CharField(max_length=500)),
                ("is_indexed", models.BooleanField(default=False)),
                ("total_files", models.IntegerField(default=0)),
                ("indexed_files", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "company_codebases",
                "ordering": ["-created_at"],
            },
        ),
    ]
