# Generated by Django 4.2.7 on 2026-03-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedcode",
            name="code_type",
            field=models.CharField(
                choices=[
                    ("sql", "SQL"),
                    ("complete_php", "Complete PHP"),
                    ("php", "PHP"),
                    ("html", "HTML"),
                    ("css", "CSS"),
                    ("js", "JavaScript"),
                ],
                max_length=15,
            ),
        ),
    ]
