# Generated by Django 4.2.7 on 2026-04-17 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("models", "0003_databaseconnection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedcode",
            name="code_type",
            field=models.CharField(
                choices=[("complete_php", "Complete PHP")], max_length=15
            ),
        ),
        migrations.CreateModel(
            name="PatternLearningEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pattern_combo_signature",
                    models.CharField(blank=True, max_length=255),
                ),
                ("selected_patterns", models.JSONField(blank=True, default=list)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("contamination", "Contamination"),
                            ("low_coverage", "Low Coverage"),
                            ("missing_memory", "Missing Memory"),
                            ("contract_reject", "Contract Reject"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phase", models.CharField(blank=True, max_length=50)),
                ("form_type", models.CharField(blank=True, max_length=20)),
                ("feature_signature", models.CharField(blank=True, max_length=255)),
                ("entity_name", models.CharField(blank=True, max_length=255)),
                ("retrieval_quality", models.FloatField(default=0.0)),
                ("pattern_coverage", models.FloatField(default=0.0)),
                ("validator_errors", models.JSONField(blank=True, default=list)),
                ("section_sizes", models.JSONField(blank=True, default=dict)),
                ("top_candidates", models.JSONField(blank=True, default=list)),
                ("failure_reason", models.TextField(blank=True)),
                ("is_blacklisted_combo", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "codebase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pattern_learning_events",
                        to="models.companycodebase",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pattern_learning_events",
                        to="models.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pattern_learning_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pattern_learning_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatternMemory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("CRUD_PATTERN", "CRUD Pattern"),
                            ("MASTER_DETAIL_PATTERN", "Master Detail Pattern"),
                            ("AJAX_PATTERN", "AJAX Pattern"),
                            ("VALIDATION_PATTERN", "Validation Pattern"),
                            ("SELECT2_PATTERN", "Select2 Pattern"),
                            ("TEMPLATE_PATTERN", "Template Pattern"),
                            ("SESSION_PATTERN", "Session Pattern"),
                            ("SECURITY_PATTERN", "Security Pattern"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("SIMPLE", "Simple"),
                            ("MASTER_DETAIL", "Master Detail"),
                            ("DEPENDENT", "Dependent"),
                        ],
                        default="ALL",
                        max_length=20,
                    ),
                ),
                (
                    "feature_signature",
                    models.CharField(blank=True, default="base", max_length=255),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("required_functions", models.JSONField(blank=True, default=list)),
                ("structure_skeleton", models.JSONField(blank=True, default=dict)),
                ("constraints", models.JSONField(blank=True, default=list)),
                ("examples", models.JSONField(blank=True, default=list)),
                ("weight", models.FloatField(default=1.0)),
                ("success_count", models.IntegerField(default=0)),
                ("failure_count", models.IntegerField(default=0)),
                ("contamination_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codebase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pattern_memories",
                        to="models.companycodebase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pattern_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pattern_memory",
                "ordering": ["pattern_type", "form_type", "-weight", "-updated_at"],
                "unique_together": {
                    ("codebase", "pattern_type", "form_type", "feature_signature")
                },
            },
        ),
    ]
