# Generated by Django 4.2.7 on 2026-05-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0004_alter_generatedcode_code_type_patternlearningevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companycodebase",
            name="index_error",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="companycodebase",
            name="index_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
